create database bd_prova1;
use bd_prova1;
create table produtos1(
ID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOME VARCHAR(80) NOT NULL,
PRECO DOUBLE(9,2) NOT NULL,
MARCA VARCHAR(80) NOT NULL,
SISTEMA VARCHAR(80) NOT NULL
)ENGINE=INNODB;

select*FROM PRODUTOS1;